skinparam{
    ArrowFontColor #F7A830
    TitleFontColor #F7A830
    ObjectFontColor #F7A830
    ObjectAttributeFontColor #F7A830
    LegendFontColor #F7A830
    InterfaceFontColor #F7A830
    HeaderFontColor #F7A830
    DomainFontColor #F7A830
    ClassStereotypeFontColor #F7A830
    ClassFontColor #F7A830
    ClassAttributeFontColor #F7A830
    CircledCharacterFontColor Black
    StartColor #9E2A86
    ActivityEndColor #9E2A86
    StateEndColor #9E2A86
    ActivityBackgroundColor #23272D
    ActivityBorderColor #9E2A86
    ActivityDiamondBackgroundColor #23272D
    ActivityDiamondBorderColor #9E2A86
    BarColor #9E2A86
    InterfaceBackgroundColor #23272D
    InterfaceBorderColor #9E2A86
    ClassBackgroundColor #23272D
    ClassArrowColor #9E2A86
    ClassBorderColor #9E2A86
    ClassHeaderBackgroundColor #2E333A
    PackageBackgroundColor #2E333A
    ArrowColor #9E2A86
    ActorBorderColor #9E2A86
    ActorBackgroundColor #23272D
    ParticipantBackgroundColor #23272D
    ParticipantBorderColor #9E2A86
    LifeLineBorderColor #9E2A86
    LifeLineBackgroundColor #2E333A
    SequenceLifeLineBorderColor #9E2A86
    SequenceLifeLineBackgroundColor #2E333A
}